# Generated by Django 4.2.5 on 2023-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_bgimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgimg',
            name='img',
            field=models.ImageField(upload_to='images/bgimg/'),
        ),
    ]
